#!/usr/bin/env bash

mkdir /tmp/virtualbox
VERSION=$(cat $HOME/.vbox_version)
mount -o loop $HOME/VBoxGuestAdditions_$VERSION.iso /tmp/virtualbox
sh /tmp/virtualbox/VBoxLinuxAdditions.run -- --force
umount /tmp/virtualbox
rmdir /tmp/virtualbox
rm $HOME/VBoxGuestAdditions_$VERSION.iso
