#!/usr/bin/env bash

mkdir /tmp/virtualbox
VERSION=$(cat $HOME/.vbox_version)
sudo -E mount -o loop $HOME/VBoxGuestAdditions_$VERSION.iso /tmp/virtualbox
sudo -E sh /tmp/virtualbox/VBoxLinuxAdditions.run -- --force
sudo -E umount /tmp/virtualbox
sudo -E rmdir /tmp/virtualbox
rm $HOME/VBoxGuestAdditions_$VERSION.iso
